version: '3.0'
volumes:
  signer-volume:
  ipc-volume:
  log-volume:
  geth-volume:
  privatenetwork-volume:
  rinkeby-volume:
  parity-volume:
services:
  rinkeby:
    build:
      context: ./rinkeby/.
    ports:
      - 8645:8545
      - 8646:8546
      - 30304:30303
  privatenetwork:
    build:
      context: ./privatenetwork/.
    ports:
      - 8545:8545
      - 8546:8546
      - 30301:30301
  signer:
    env_file:
      - ./environment/signer.env
    build:
      context: ./node_modules/gittoken-signer/.
    ipc: host
    volumes:
      - signer-volume:/keystore/
      - ipc-volume:/tmp/
  webhookmgr:
    ports:
      - 3000:3000
    env_file:
      - ./environment/webhook.env
    build:
      context: ./node_modules/gittoken-webhook-manager/.
    ipc: signer
    volumes:
      - log-volume:/db
      - ipc-volume:/tmp/
  registry:
    ports:
      - 3001:3001
    env_file:
      - ./environment/registry.env
    build:
      context: ./node_modules/gittoken-registry/.
    ipc: signer
    volumes:
      - ipc-volume:/tmp/
  mysql:
    ports:
      - 3306:3306
    env_file:
      - ./environment/mysql.env
    image:
      mysql
  geth:
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    image: ethereum/client-go
    volumes:
      - geth-volume:/root/.ethereum
    command: --testnet -wsaddr 0.0.0.0 -ws -wsorigins "*" --wsapi="db,eth,net,web3" --rpcaddr 0.0.0.0 --rpc --rpccorsdomain "*" --rpcapi="db,eth,net,web3" --fast
  parity:
    ports:
      - 8080:8080
      - 8180:8180
      - 8545:8545
      - 8546:8546
      - 30303:30303
    build:
      context: ./parity/deploy/.
    volumes:
      - parity-volume:/root/parity
    command: --rpccorsdomain="*" --geth --config /root/parity/config.toml
