[parity]
mode = "last"
chain = "/root/parity/chain.json"
keys_path = "/root/parity/keys"

base_path = "/root/parity"

# [account]
# unlock = ["024138ba30f69f108a4e0aad9d51b4b4a4e03dd7"]
# password = ["/root/parity/.pk"]

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"
path = "/root/parity/signer"

[rpc]
interface = "0.0.0.0"
cors = "*"
disable = false
port = 8545
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal"]
hosts = ["all"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[ipc]
disable = false
path = "/root/parity/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]


[ipfs]
interface = "0.0.0.0"
cors = "*"

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
id = 9
bootnodes = [
"enode://ae7779e36d3bb9d6d650f8b441c0249b45fb7764e3d391f556735c3da34a54690a498bdfdc49095ae2a2f182ad40badb11f7b17fc00c62772a295abe331f4175@172.18.0.3:30303"
]
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false
