[parity]
mode = "last"
chain = "/root/parity/chain.json"
keys_path = "/root/parity/keys"

base_path = "/root/parity"

[account]
unlock = ["0xd6c05d314086488b757c3312e5d8a036fffdc082"]
password = ["/root/parity/keys/.pk"]

[ui]
force = false
disable = false
port = 8180
interface = "0.0.0.0"
path = "/root/parity/signer"

[rpc]
interface = "0.0.0.0"
cors = "*"
disable = false
port = 8545
apis = ["web3", "eth", "net", "parity", "traces", "rpc"]
hosts = ["all"]

[websockets]
disable = false
port = 8546
interface = "local"
origins = ["*"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]

[ipc]
disable = false
path = "/root/parity/jsonrpc.ipc"
apis = ["web3", "eth", "net", "parity", "parity_accounts", "personal", "traces", "rpc", "secretstore"]


[ipfs]
interface = "0.0.0.0"
cors = "*"

[network]
port = 30303
min_peers = 25
max_peers = 50
nat = "any"
id = 9
bootnodes = []
discovery = true
warp = true
allow_ips = "all"
snapshot_peers = 0
max_pending_peers = 64
no_serve_light = false
reserved_only = false

[mining]
reseal_min_period = 0
